### ISSUE TITLE
Signout redirect to home page

### ISSUE THREAD

**Issue by Markz878** [damienbod/Blazor.BFF.AzureAD.Template#14]
Hi Damien, thanks for this.

Could you give any hints on how to redirect user back to the home page after sign out?
I have tried all sort of tricks found on the internet, but I can't get past the "You signed out of your account
It's a good idea to close all browser windows." page at https://login.microsoftonline.com/common/oauth2/v2.0/logoutsession.

I'm using personal Microsoft accounts in my Azure Ad App registration, I read somewhere that that might prevent the redirect..?
Any advice on this is appreciated, thanks!

**Comment by damienbod** [comment]
This should work when you deploy the app, fails on localhost. The property needs to be set correctly on the Azure App registration.
